# Project information
site_name: Reciprocal n-body Collision Avoidance
site_author: Abdellatif BELMADY
edit_uri: https://github.com/abdellatif-belmady/R-Project/tree/main/docs
site_description: >-
  Pour acquérir un sens de la pratique, et s’ouvrir à l’environnement professionnel, nous sommes amenés à rédiger une note de synthèse de notre traitement du Heetch dataset incluant la démarche, les principaux résultats et les conclusions.
  Dans ce cadre-là, vient ce rapport auquel nous allons synthétiser le travail fait.


# Repository
repo_name: abdellatif-belmady/Reciprocal-n-body-Collision-Avoidance
repo_url: https://github.com/abdellatif-belmady/Reciprocal-n-body-Collision-Avoidance

# Copyright
copyright: Copyright &copy; 2022 - 2023 Abdellatif BELMADY

# Configuration
theme:
  language: fr


  logo: assets/images/logo.png

  favicon: assets/images/logo.png

  name: material
  
  features:
    - content.code.copy
    - content.action.edit
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    #- navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.expand
    - navigation.footer
    # - toc.integrate
  palette:
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - tags

# Extensions
markdown_extensions:
  - abbr
  - extra
  - meta
  - smarty
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences





# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/abdellatif-belmady
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/abdellatif-belmady-ab999a133/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/abdellatif.belmady
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@otherways8368/featured
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/abdellatifbelmady/
     
extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - index.md
  









